apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  name: ccpdemo
spec:
  forProvider:
    region: 
    tags:
      project: CCP
      env: dev
      aws: eks
  providerConfigRef:
    name: newawsconfig
