apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  name: ccpdemo26092023test
spec:
  forProvider:
    region: us-west-2
    tags:
      project: CCP
      env: dev
      aws: eks
  providerConfigRef:
    name: awsconfig
