apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  name: democcp-testing-getportio
spec:
  forProvider:
    region: us-west-1
    tags:
      project: CCP
      env: dev
      aws: eks
  providerConfigRef:
    name: newawsconfig
